url: https://kimbergee.github.io
baseurl: ""

# Site settings
title: Kimber's Portfolio
email: hello@kimbergee.com
description: "web developer"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/kimbergee
  - title: linkedin
    url: https://www.linkedin.com/in/kimbergee
  - title: twitter
    url: http://twitter.com/kimberzama
  - title: facebook
    url: http://facebook.com/kimbergee
  - title: instagram
    url: http://instagram.com/misskimbers


# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
